# Generated by Django 5.1.4 on 2025-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='startups',
            field=models.JSONField(default=list),
        ),
    ]
