# Generated by Django 5.1.4 on 2025-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_startups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('owners', models.JSONField(default=list)),
                ('startupid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('picture', models.CharField(default='', max_length=500)),
                ('stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Стартап',
                'verbose_name_plural': 'Стартапы',
            },
        ),
    ]
