# Generated by Django 5.1.4 on 2025-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
