# Generated by Django 5.1.4 on 2025-01-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_startups_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='startups',
            new_name='startu',
        ),
    ]
