# Generated by Django 5.1.4 on 2025-01-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_startups_users_startu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='startu',
            new_name='startups',
        ),
    ]
