# Generated by Django 5.1.4 on 2025-01-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_startu_users_startups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startups',
            old_name='stars',
            new_name='responses',
        ),
        migrations.AlterField(
            model_name='users',
            name='startups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startups'),
        ),
    ]
