# Generated by Django 5.1.4 on 2025-01-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_users_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='startups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.startups'),
        ),
    ]
