# Generated by Django 5.1.4 on 2025-01-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_users_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='owners',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='users',
            name='startups',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.startups'),
        ),
    ]
