# Generated by Django 5.1.4 on 2025-01-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_startups_owners_alter_users_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='owners',
            field=models.JSONField(default=list),
        ),
    ]
