# Generated by Django 5.1.4 on 2025-01-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_startups_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startups',
            name='owners',
        ),
    ]
