# Generated by Django 5.1.4 on 2025-01-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_startups_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='startups',
        ),
        migrations.AddField(
            model_name='users',
            name='startups',
            field=models.ManyToManyField(to='main.startups'),
        ),
    ]
