# Generated by Django 5.1.4 on 2025-01-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_users_startups_users_startups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='startups',
        ),
        migrations.AddField(
            model_name='users',
            name='startups',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.startups'),
        ),
    ]
