# Generated by Django 5.1.4 on 2025-01-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_users_startups_users_startups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='startups',
        ),
        migrations.CreateModel(
            name='StartupOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_startups', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='main.startups')),
            ],
            options={
                'verbose_name': 'Владелец стартапа',
                'verbose_name_plural': 'Владельцы стартапов',
                'unique_together': {('owner', 'startup')},
            },
        ),
        migrations.CreateModel(
            name='StartupParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_startups', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.startups')),
            ],
            options={
                'verbose_name': 'Участник стартапа',
                'verbose_name_plural': 'Участники стартапов',
                'unique_together': {('participant', 'startup')},
            },
        ),
    ]
