# Generated by Django 5.1.4 on 2025-01-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_users_startups_startupowners_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartupParticipants',
            new_name='InterestedParties',
        ),
    ]
