# Generated by Django 5.1.4 on 2025-01-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_startupparticipants_interestedparties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestedparties',
            old_name='participant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='startupowners',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='interestedparties',
            unique_together={('user', 'startup')},
        ),
        migrations.AlterUniqueTogether(
            name='startupowners',
            unique_together={('user', 'startup')},
        ),
    ]
