# Generated by Django 5.1.4 on 2025-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_participant_interestedparties_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='social_networks',
            field=models.CharField(default='tg', max_length=100),
            preserve_default=False,
        ),
    ]
