# Generated by Django 5.1.4 on 2025-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_users_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparties',
            name='message',
            field=models.CharField(default='message', max_length=500),
            preserve_default=False,
        ),
    ]
