# Generated by Django 5.1.4 on 2025-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_interestedparties_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparties',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
