# Generated by Django 5.1.4 on 2025-01-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_interestedparties_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedparties',
            name='status',
        ),
    ]
